name: 'f1warehouse'
version: '1.0.0'
config-version: 2
profile: 'f1warehouse_duckdb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
log-path: "logs"
clean-targets:         # directories to be removed by `dbt clean`
  - "dbt_packages"
  - "target"
  - "logs"

vars:
  start_date: '1900-01-01'
  end_date: '3000-12-31'

models:
  +post-hook:
    - "{{ dagster.log_column_level_metadata() }}"
  f1warehouse:
      core:
        +schema: core
        +materialized: incremental
        +on_schema_change: append_new_columns
      stage:
        +materialized: view
        ergast:
          +schema: stage_ergast
