f1warehouse_duckdb:
  target: "{{ env_var('DBT_ENVIRONMENT', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      schema: public
      threads: 4
      path: "{{ env_var('DATA_DIR', '../data') }}/f1.duckdb"
      external_root: "{{ env_var('DATA_DIR', '../data') }}/"
