[tool.poetry]
name = "f1warehouse"
version = "0.1.0"
description = "Some experimenting with dbt/DuckDB using Ergast API as main source."
authors = ["frizzleqq"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"
duckdb = "^0.4.0"
pandas = "^1.4.3"
dbt-duckdb = "^1.1.4"

[tool.poetry.dev-dependencies]
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
