[tool.poetry]
name = "f1-dbt-duckdb"
version = "0.1.0"
description = "Some experimenting with dbt/DuckDB using Ergast API as main source."
authors = ["frizzleqq"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "2.27.1"
duckdb = "^0.5.0"
pandas = "^1.5.1"
dbt-duckdb = "^1.2.3"
# as of 2.3.3 airflow is not compatible in same py environment as dbt (due to jinja 3.x)
# poetry installs all extras for airflow, so may switch to regular setup
apache-airflow = {version = "2.3.2", extras = ["common.sql"]}
sqlfluff-templater-dbt = "^1.4.5"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
