# This workflow will:
#   - install Python dependencies
#   - lint Python code
#   - extract some data from ergast
#   - run dbt build
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Ergast data load

env:
  DATA_DIR: /tmp/data

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: make requirements
    - name: Lint Python code
      run: make test
    - name: Lint SQL code
      run: |
        mkdir -p $DATA_DIR
        make lint-sql
    - name: Run ergast job
      run: make load
